---
title: "HiSSEplots-cetaceans"
output:
  pdf_document: default
  html_notebook: default
---
```{r}
# Generating colorblind friendly palette (30)
library(RColorBrewer)
n <- 30
colrs <- brewer.pal.info[brewer.pal.info$colorblind == TRUE, ]
col_vec = unlist(mapply(brewer.pal, colrs$maxcolors, rownames(colrs)))
col <- sample(col_vec, n)
area <- rep(1,n)
pie(area, col = col)
```


```{r setup, include=FALSE}
# Libraries needed
rm(list=ls())
all.lib<-c("ape","diversitree","phytools", "hisse","ggplot2","gridExtra","ggpubr","numDeriv","reshape2","ggthemes","scales") # add libraries here
lapply(all.lib,require,character.only=TRUE)

#colorpalette-black
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7","#CC6666", "#9999CC", "#66CC99","#999999")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7","#CC6666", "#9999CC", "#66CC99","#999999", "#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888" )

```

#Cetacean dataset only
#set the working directory and parameters
```{r}
setwd("/Users/nhans/DiversificationPaper/Diversification2020")
n.step<-15000
k.vec<- 2^seq(1,9,by=1)
sizeofk.vec<-length(k.vec)

# 20 % of n.step
start.pos<-0.2*n.step

# Thinning the MCMC chain
thin<-sequence((n.step-start.pos)/10,1,10) # thinning interval - 10
l.thin<-length(thin)

#parameters for each model
hisse.parnames<-c("tau1","tau2", "tau3", "tau4", "ep1","ep2", "ep3", "ep4", "q12","q13","q14","q21","q23","q24","q31","q32","q34","q41","q42","q43")
reparnames<-c("lambda1","lambda2", "lambda3", "lambda4", "mu1","mu2", "mu3", "mu4", "q12","q13","q14","q21","q23","q24","q31","q32","q34","q41","q42","q43")

```
 
# Loading the dataset - NO CLONE 

```{r}
# NO CLONES-----------------------------------------Required for getting max eigen value
# No Clone dataset - discard 20% burnin
his.no.clone<-read.csv("/Users/nhans/DiversificationPaper/Diversification2020/posteriorsMCMCwhales_Jul_15_21_50000.csv")[(start.pos+1):n.step,2:21]
#his.no.clone<-read.csv("/Users/nhans/DiversificationPaper/Diversification2020/posteriorsMCMCwhales_Jul_20_21_1e+05.csv")[(startpos+1):n.step,2:21]
#reparnames<-colnames(his.no.clone) # Because i forgot to re-parameterize in the code but named it --- so fix the code on cluster to avoid having to do
colnames(his.no.clone)<-hisse.parnames

# 1) TURNOVER and EXTINCTION 
# Thinning out the posteriors 
thin.his.no.clone<-matrix(nrow = l.thin, ncol = 20) # empty matrix 
# thinning out the posterior (no clone)
count<-0
for (t in thin){
 count<-count+1
 thin.his.no.clone[count,1]<-eval(parse(text=paste("his.no.clone","$tau1",sep="")))[t]
 thin.his.no.clone[count,2]<-eval(parse(text=paste("his.no.clone","$tau2",sep="")))[t]
 thin.his.no.clone[count,3]<-eval(parse(text=paste("his.no.clone","$tau3",sep="")))[t]
 thin.his.no.clone[count,4]<-eval(parse(text=paste("his.no.clone","$tau4",sep="")))[t]
 
 thin.his.no.clone[count,5]<-eval(parse(text=paste("his.no.clone","$ep1",sep="")))[t]
 thin.his.no.clone[count,6]<-eval(parse(text=paste("his.no.clone","$ep2",sep="")))[t]
 thin.his.no.clone[count,7]<-eval(parse(text=paste("his.no.clone","$ep3",sep="")))[t]
 thin.his.no.clone[count,8]<-eval(parse(text=paste("his.no.clone","$ep4",sep="")))[t]
 
 thin.his.no.clone[count,9]<-eval(parse(text=paste("his.no.clone","$q12",sep="")))[t]
 thin.his.no.clone[count,10]<-eval(parse(text=paste("his.no.clone","$q13",sep="")))[t]
 thin.his.no.clone[count,11]<-eval(parse(text=paste("his.no.clone","$q14",sep="")))[t]
 thin.his.no.clone[count,12]<-eval(parse(text=paste("his.no.clone","$q21",sep="")))[t]
 
 thin.his.no.clone[count,13]<-eval(parse(text=paste("his.no.clone","$q23",sep="")))[t]
 thin.his.no.clone[count,14]<-eval(parse(text=paste("his.no.clone","$q24",sep="")))[t]
 thin.his.no.clone[count,15]<-eval(parse(text=paste("his.no.clone","$q31",sep="")))[t]
 thin.his.no.clone[count,16]<-eval(parse(text=paste("his.no.clone","$q32",sep="")))[t]
 
 thin.his.no.clone[count,17]<-eval(parse(text=paste("his.no.clone","$q34",sep="")))[t]
 thin.his.no.clone[count,18]<-eval(parse(text=paste("his.no.clone","$q41",sep="")))[t]
 thin.his.no.clone[count,19]<-eval(parse(text=paste("his.no.clone","$q42",sep="")))[t]
 thin.his.no.clone[count,20]<-eval(parse(text=paste("his.no.clone","$q43",sep="")))[t]
 colnames(thin.his.no.clone)<-hisse.parnames
}

eigen.max.his.noclone<-max(eigen(cov(thin.his.no.clone))$values)
eigen.max.his.noclone
# [1] 0.06681723 with transition rates
# [1] 0.048744829 without transition rates 

# 2) REPARAMETERIZATION to LAMBDA AND MU
# Reparameterizing the thinned no clones
lambda1.his.noclone<-thin.his.no.clone[,1]/(1+thin.his.no.clone[,5])
lambda2.his.noclone<-thin.his.no.clone[,2]/(1+thin.his.no.clone[,6])
lambda3.his.noclone<-thin.his.no.clone[,3]/(1+thin.his.no.clone[,7])
lambda4.his.noclone<-thin.his.no.clone[,4]/(1+thin.his.no.clone[,8])

mu1.his.noclone<- lambda1.his.noclone* thin.his.no.clone[,5]
mu2.his.noclone<- lambda2.his.noclone* thin.his.no.clone[,6]
mu3.his.noclone<- lambda3.his.noclone* thin.his.no.clone[,7]
mu4.his.noclone<- lambda4.his.noclone* thin.his.no.clone[,8]

eigen.max.his.noclone.repara<-max(eigen(cov(cbind(lambda1.his.noclone,lambda2.his.noclone,lambda3.his.noclone,lambda4.his.noclone,mu1.his.noclone,mu2.his.noclone,mu3.his.noclone,mu4.his.noclone,thin.his.no.clone[,9:20])))$values)
eigen.max.his.noclone.repara
# [1] 0.06161159 with transition rates 
# [1] 0.06681723 - without transition rates 

```
 
# Turnover and extinction fraction
```{r}
# CLONES----------------------------------------------------------------------------------
# Load and discard 20% burnin
for (k in k.vec){
  temp.dat<-read.csv(paste("/Users/nhans/DiversificationPaper/Diversification2020/clone_taxa_MCMCwhales_",k,"_Jul_15_21_50000.csv",sep=""))[(start.pos+1):n.step,2:21]
  colnames(temp.dat)<-hisse.parnames
  assign(paste("his.clone.cet",k,sep=""), temp.dat)
}

# _Jul_21_21_15000
#_Jul_15_21_50000
#Format: 1=0A, 2=1A, 3=0B, 4=1B.

# SEPARATING EACH PARAMETER INTO A MATRIX WITH EACH CLONE VALUES 
# Assign empty matrix for 4 turnover rates and 4 extinction fractions 
for (i in 1:4){
  temp.mat<-matrix(NA, ncol=sizeofk.vec, nrow=l.thin,dimnames=list(as.character(1:l.thin),as.character(k.vec)))
  assign(paste("tau",i, ".his.clone",sep = ""), temp.mat) # turnover rates
  assign(paste("ep",i, ".his.clone",sep = ""), temp.mat)  # extinction fraction
  #assign(paste("trans",i, ".his.clone",sep = ""), temp.mat)  # transition rates (note that there are 12)
}
temp.mat.hisse<-matrix(nrow = l.thin,ncol = 20) # empty matrix to save thinned dataset (20x20) for each clone

# THINNING
## 1) Saving turnover rates, extinction fractions in different matrix
counter<-0
for(k in k.vec)
{
  counter<-counter+1
  rowcount<-0
  for(t in thin){
  rowcount<-rowcount+1
  tau1.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$tau1",sep="")))[t]
  tau2.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$tau2",sep="")))[t]
  tau3.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$tau3",sep="")))[t]
  tau4.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$tau4",sep="")))[t]

  ep1.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$ep1",sep="")))[t]
  ep2.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$ep2",sep="")))[t]
  ep3.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$ep3",sep="")))[t]
  ep4.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$ep4",sep="")))[t]
  
  # Transition rates
  #trans1.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$q12",sep="")))[t]
  #trans2.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$q13",sep="")))[t]
  #trans3.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$q14",sep="")))[t]
  #trans4.his.clone[rowcount,counter]<-eval(parse(text=paste("his.clone.cet",k,"$q21",sep="")))[t]
  # The above and 8 not needed for our plots as the matrix below has the transistion rates already
  
  temp.mat.hisse[rowcount,] <- as.matrix(eval(parse(text=paste("his.clone.cet",k,sep = "")))[t,])
  }
  colnames(temp.mat.hisse)<-hisse.parnames
  assign(paste("thinnedHisClone", k ,sep =""), temp.mat.hisse)
}

# 2) Reparameterization 
#----------------------------------------------- Reparameterizing from tau and ep to lambda and mu
# lambda1<-tau1/(1+ep1)
# mu1<- lambda1* ep1
#Reparameterizing
lambda1.his.clone<-tau1.his.clone/(1+ep1.his.clone)
lambda2.his.clone<-tau2.his.clone/(1+ep2.his.clone)
lambda3.his.clone<-tau3.his.clone/(1+ep3.his.clone)
lambda4.his.clone<-tau4.his.clone/(1+ep4.his.clone)

mu1.his.clone<- lambda1.his.clone* ep1.his.clone
mu2.his.clone<- lambda2.his.clone* ep2.his.clone
mu3.his.clone<- lambda3.his.clone* ep3.his.clone
mu4.his.clone<- lambda4.his.clone* ep4.his.clone

# Recombining the dataset with lambda, mu and q for each clone
temp.mat.hisse<-matrix(nrow = l.thin,ncol = 20)
count<-0
for (k in k.vec){
   count<-count+1
   temp.mat.hisse[,1] <-lambda1.his.clone[,count]
   temp.mat.hisse[,2]<-lambda2.his.clone[,count]
   temp.mat.hisse[,3]<-lambda3.his.clone[,count]
   temp.mat.hisse[,4]<-lambda4.his.clone[,count]
   temp.mat.hisse[,5]<-mu1.his.clone[,count]
   temp.mat.hisse[,6]<-mu2.his.clone[,count]
   temp.mat.hisse[,7]<-mu3.his.clone[,count]
   temp.mat.hisse[,8]<-mu4.his.clone[,count]
   
   all.trans.temp<- eval(parse(text=paste("thinnedHisClone",k,sep = "")))[,9:20]
   temp.mat.hisse[,9:20]<- all.trans.temp
   colnames(temp.mat.hisse)<-reparnames
   assign(paste("thinedHisRepara",k,sep = ""),temp.mat.hisse)
}


```

# HiSSE plots together (1)
```{r}

#-1)--------------------------------------------- plots for tau and ep
# separating clone 2 for 4 turnover rates 
tau.2<-(cbind(tau1.his.clone[,1],tau2.his.clone[,1],tau3.his.clone[,1],tau4.his.clone[,1]))
colnames(tau.2)<-c("tau1","tau2", "tau3", "tau4")
row.names(tau.2)<-c(rep(2,l.thin))

# separating clone 2 for 4 extinction fractions
ep.2<-(cbind(ep1.his.clone[,1],ep2.his.clone[,1],ep3.his.clone[,1],ep4.his.clone[,1]))
colnames(ep.2)<-c("ep1","ep2", "ep3", "ep4")
row.names(ep.2)<-c(rep(2,l.thin))

## Clone 512
# separating clone 512 for 4 turnover rates
tau.512<-(cbind(tau1.his.clone[,9],tau2.his.clone[,9],tau3.his.clone[,9],tau4.his.clone[,9]))
colnames(tau.512)<-c("tau1","tau2", "tau3", "tau4")
row.names(tau.512)<-c(rep(512,l.thin))

# separating clone 512 for 4 extinction fractions
ep.512<-(cbind(ep1.his.clone[,9],ep2.his.clone[,9],ep3.his.clone[,9],ep4.his.clone[,9]))
colnames(ep.512)<-c("ep1","ep2", "ep3", "ep4")
row.names(ep.512)<-c(rep(512,l.thin))


tau.all<-rbind(melt(tau.2),melt(tau.512))
colnames(tau.all)<-c("Var1","Rates","value")

ep.all<-rbind(melt(ep.2),melt(ep.512))
colnames(ep.all)<-c("Var1","Rates","value")

morecols<-c("lightseagreen","lightsalmon4","slateblue4","red4","#004949","#490092","#6db6ff","#924900")
h1.turn<-ggplot(tau.all, aes(x=value,group=Rates,fill=Rates)) + 
  geom_density(alpha=.5)+
  facet_wrap(~ Var1)+
  ggtitle("HiSSE turnover rates")+
  xlim(0,0.4)+
  #ylim(0,100)+
  xlab(expression(tau))+
  ylab("Density")+
  scale_fill_manual(values=morecols[1:4])+
  theme_pubclean()

h2.turn<-ggplot(ep.all, aes(x=value,group=Rates,fill=Rates)) + 
  geom_density(alpha=.5)+
  facet_wrap(~ Var1)+
  ggtitle("HiSSE extinction fractions ")+
  #xlim(0,0.75)+
  ylim(0,50)+
  xlab(expression(epsilon))+
  ylab("Density")+
  scale_fill_manual(values=morecols[5:8])+
  theme_pubclean()

library(ggpubr)
figure7<-ggarrange(nrow = 2,h1.turn,h2.turn, labels = c("A","B"))


ggsave(filename="Figure7_high.png", plot=figure7, device="png",dpi=700)
figure7
#----------------------------------------------------------------------
```

# 2)

```{r}
#2)----------------------------------------------------------------------plots for lambda and mu

# separating clone 2 for speciation 4 lambda
lambda.2<-(cbind(lambda1.his.clone[,1],lambda2.his.clone[,1],lambda3.his.clone[,1],lambda4.his.clone[,1]))
colnames(lambda.2)<-c("lambda1","lambda2", "lambda3", "lambda4")
row.names(lambda.2)<-c(rep(2,l.thin))


# separating clone 2 for exinction 4 mu
mu.2<-(cbind(mu1.his.clone[,1],mu2.his.clone[,1],mu3.his.clone[,1],mu4.his.clone[,1]))
colnames(mu.2)<-c("mu1","mu2", "mu3", "mu4")
row.names(mu.2)<-c(rep(2,l.thin))

# separating clone 512 for speciation 4 lambda
lambda.512<-(cbind(lambda1.his.clone[,9],lambda2.his.clone[,9],lambda3.his.clone[,9],lambda4.his.clone[,9]))
colnames(lambda.512)<-c("lambda1","lambda2", "lambda3", "lambda4")
row.names(lambda.512)<-c(rep(512,l.thin))

# separating clone 512 for exinction 4 mu
mu.512<-(cbind(mu1.his.clone[,9],mu2.his.clone[,9],mu3.his.clone[,9],mu4.his.clone[,9]))
colnames(mu.512)<-c("mu1","mu2", "mu3", "mu4")
row.names(mu.512)<-c(rep(512,l.thin))


lambda.all<-rbind(melt(lambda.2),melt(lambda.512))
colnames(lambda.all)<-c("Var1","Rates","value")


mu.all<-rbind(melt(mu.2),melt(mu.512))
colnames(mu.all)<-c("Var1","Rates","value")

h1.repara<-ggplot(lambda.all, aes(x=value,group=Rates,fill=Rates)) + 
  geom_density(alpha=.5)+
  facet_wrap(~ Var1)+
  ggtitle("HiSSE speciation rates")+
  xlim(0,0.4)+
  ylim(0,200)+
  xlab(expression(lambda))+
  ylab("Density")+
  scale_fill_manual(values=morecols[1:4])+
  theme_pubclean()
 #theme(plot.title = element_text(size=18),axis.text.y=element_blank(),axis.title.x=element_text(size = 20),axis.title.y=element_text(size = 16))

h2.repara<-ggplot(mu.all, aes(x=value,group=Rates,fill=Rates)) + 
  geom_density(alpha=.5)+
  facet_wrap(~ Var1)+
  ggtitle("HiSSE extinction rates")+
   xlim(0,0.15)+
   ylim(0,200)+
  xlab(expression(mu))+
  ylab("Density")+
  scale_fill_manual(values=morecols[5:8])+
  theme_pubclean()
  #theme(plot.title = element_text(size=18),axis.text.y=element_blank(),axis.title.x=element_text(size = 20),axis.title.y=element_text(size = 16))

figureS1<-ggarrange(nrow = 2,h1.repara,h2.repara, labels = c("A","B"))

#ggarrange(nrow = 2,h1,h2, labels = c("A","B")) %>%
#ggexport(filename = "Figure7.jpeg")
ggsave(filename="FigureS1_high.png", plot=figureS1, device="png",dpi=600)
figureS1
```

# 3)Eigenvalues and variances
```{r}
#--------------------------------------EigenValues and variances for turnover and extinction fraction
# HiSSE eigenvalues and variances together
eigenvals.hisse.turn<-vector(length =length(k.vec))

# original datasets has all clones separate, parameters together
count.hi<-0
for(k in k.vec){
  count.hi<-count.hi+1
  his.temp<-eval(parse(text=paste("thinnedHisClone",k,sep="")))
  eigenvals.hisse.turn[count.hi]<-(eigen(cov(his.temp))$values[1])/eigen.max.his.noclone
}
dat.eig.his<-data.frame(k.vec,eigenvals.hisse.turn)

# tau1.his.clone has tau1 with all clones
# named it like that so it melts correctly without changing names again
tau1<-apply(tau1.his.clone,2, var) 
tau2<-apply(tau2.his.clone,2, var)
tau3<-apply(tau3.his.clone,2, var)
tau4<-apply(tau4.his.clone,2, var)
tau.var.hisse<-melt(t(data.frame(tau1,tau2,tau3,tau4)))

# named it like that so it melts correctly without changing naems again
ep1<-apply(ep1.his.clone,2, var) 
ep2<-apply(ep2.his.clone,2, var)
ep3<-apply(ep3.his.clone,2, var)
ep4<-apply(ep4.his.clone,2, var)
ep.var.hisse<-melt(t(data.frame(ep1,ep2,ep3,ep4)))

colnames(tau.var.hisse)<- c("Rates" ,"clone","value")
colnames(ep.var.hisse)<- c("Rates","clone" ,"value")



favcol<-c("skyblue4","aquamarine4")
h3.turn<-ggplot(data=dat.eig.his, aes(x=k.vec,y=eigenvals.hisse.turn)) +
  geom_line(color="aquamarine4",size=1) +
  geom_point(color="aquamarine4",size=3)+
  ggtitle("Hisse eigenvalues")+
  ylim(0,max(eigenvals.hisse.turn))+
  xlab("number of clones")+
  ylab("eigenvalues ")+
  theme_pubclean()

h4.turn<-ggplot(tau.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
  geom_line(size=1) +
  geom_point(size=2)+
  ggtitle("Marginal variance-turnover rates")+
  xlab("number of clones")+
  ylab("Marginal variance ")+
  scale_colour_manual(values=cbbPalette[1:4])+
  theme_pubclean()

h5.turn<-ggplot(ep.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
  geom_line(size=1) +
  geom_point(size=2)+
  ggtitle("Marginal variance- extinction fractions")+
  xlab("number of clones")+
  ylab("Marginal variance")+
  scale_colour_manual(values=cbbPalette[9:12])+
  theme_pubclean()

figure8<- ggarrange( h4.turn,h5.turn,h3.turn,
                    labels = c("A", "B","C"),
                    ncol = 2, nrow = 2)
figure8
ggsave(filename="Figure8_high.png", plot=figure8, device="png",dpi=500)
```
# 4))
```{r}
#--------------------------------------EigenValues and variances for lambda and mu
# HiSSE eigenvalues and variances together
eigenvals.hisse.repara<-vector(length =length(k.vec))

count.hi<-0
for(k in k.vec){
  count.hi<-count.hi+1
  his.temp<-eval(parse(text=paste("thinedHisRepara",k,sep="")))
  eigenvals.hisse.repara[count.hi]<-(eigen(cov(his.temp))$values[1])/eigen.max.his.noclone.repara
}
dat.eig.his.repara<-data.frame(k.vec,eigenvals.hisse.repara)

# Marginal variances
# named it like that so it melts correctly without changing naems again
lambda1<-apply(lambda1.his.clone,2, var) 
lambda2<-apply(lambda2.his.clone,2, var)
lambda3<-apply(lambda3.his.clone,2, var)
lambda4<-apply(lambda4.his.clone,2, var)
lambda.var.hisse<-melt(t(data.frame(lambda1,lambda2,lambda3,lambda4)))

# named it like that so it melts correctly without changing naems again
mu1<-apply(mu1.his.clone,2, var) 
mu2<-apply(mu2.his.clone,2, var)
mu3<-apply(mu3.his.clone,2, var)
mu4<-apply(mu4.his.clone,2, var)
mu.var.hisse<-melt(t(data.frame(mu1,mu2,mu3,mu4)))

#
#trans1<-apply(trans1.his.clone,2, var) 
#trans2<-apply(trans2.his.clone,2, var)
#trans3<-apply(trans3.his.clone,2, var)
#trans4<-apply(trans4.his.clone,2, var)
#trans.var.hisse<-melt(t(data.frame(trans1,trans2,trans3)))
#trans.var.hisse<-melt(t(trans1))

colnames(lambda.var.hisse)<- c("Rates" ,"clone","value")
colnames(mu.var.hisse)<- c("Rates","clone" ,"value")
#colnames(trans.var.hisse)<- c("Rates","clone" ,"value")


favcol<-c("skyblue4","aquamarine4")
h3.repara<-ggplot(data=dat.eig.his.repara, aes(x=k.vec,y=eigenvals.hisse.repara)) +
    geom_line(color="skyblue4",size=1) +
    geom_point(color="skyblue4",size=3)+
    ggtitle("Hisse eigenvalues")+
  xlab("number of clones")+
  ylab("eigenvalue ")+
  theme_pubclean()
  #  theme(plot.title = element_text(size=15),axis.text.y=element_blank(),axis.title.x=element_text(size = 15),axis.title.y=element_text(size = 15))


h4.repara<-ggplot(lambda.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
    geom_line(size=1) +
    geom_point(size=2)+
    ggtitle("Marginal variance-speciation")+
  xlab("number of clones")+
  ylab("Marginal variance ")+
   scale_colour_manual(values=cbbPalette[13:16])+
  theme_pubclean()+
theme(legend.text=element_text(size=7),
        legend.title=element_text(size=7))
  #theme(legend.key.size = unit(0.1, "cm"))
  #  theme(plot.title = element_text(size=14),axis.text.y=element_blank(),axis.title.x=element_text(size = 14),axis.title.y=element_text(size = 14))

h5.repara<-ggplot(mu.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
    geom_line(size=1) +
    geom_point(size=2)+
    ggtitle("Marginal variance- extinction")+
  xlab("number of clones")+
  ylab("Marginal variance")+
   scale_colour_manual(values=cbbPalette[17:20])+
  theme_pubclean()+
  theme(legend.text=element_text(size=8),
        legend.title=element_text(size=8))


# # Transition rates 
# ggplot(trans.var.hisse, aes(x=clone,y=value)) +
#     geom_line(size=1) +
#     geom_point(size=2)+
#     ggtitle("Marginal variance- transition")+
#   xlab("number of clones")+
#   ylab("Marginal variance")+
#    scale_colour_manual(values=cbbPalette)+
#   theme_pubclean()

figureS2 <- ggarrange( h4.repara,h5.repara,h3.repara,
                    labels = c("A", "B","C"),
                    ncol = 2, nrow = 2)
figureS2
ggsave(filename="FigureS2_high.png", plot=figureS2, device="png",dpi=500)
```


```{r}
figureTogether<-ggarrange(nrow = 2,ncol = 2, h1.turn,h1.repara,h2.turn,h2.repara,labels = c("A","B","C","D"))

h3.turn<-ggplot(data=dat.eig.his, aes(x=k.vec,y=eigenvals.hisse.turn)) +
  geom_line(color="aquamarine4",size=1) +
  geom_point(color="aquamarine4",size=3)+
  ggtitle("Eigenvalues - Original")+
  ylim(0,max(eigenvals.hisse.turn))+
  xlab("number of clones")+
  ylab("eigenvalues ")+
  theme_pubclean()

h3.repara<-ggplot(data=dat.eig.his, aes(x=k.vec,y=eigenvals.hisse.repara)) +
    geom_line(color="skyblue4",size=1) +
    geom_point(color="skyblue4",size=3)+
    ggtitle("Eigenvalues - Reparameterized")+
  xlab("number of clones")+
  ylab("eigenvalue ")+
  theme_pubclean()


h4.turn<-ggplot(tau.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
  geom_line(size=1) +
  geom_point(size=2)+
  ggtitle("Marginal variance-tau ")+
  xlab("number of clones")+
  ylab("Marginal variance ")+
  scale_colour_manual(values=cbbPalette)+
  theme_pubclean()

h5.turn<-ggplot(ep.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
  geom_line(size=1) +
  geom_point(size=2)+
  ggtitle("Marginal variance- epsilon")+
  xlab("number of clones")+
  ylab("Marginal variance")+
  scale_colour_manual(values=cbbPalette[9:12])+
  theme_pubclean()

h4.repara<-ggplot(lambda.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
    geom_line(size=1) +
    geom_point(size=2)+
    ggtitle("Marginal variance-lambda")+
  xlab("number of clones")+
  ylab("Marginal variance ")+
   scale_colour_manual(values=cbbPalette[13:16])+
  theme_pubclean()+
theme(legend.text=element_text(size=7),
        legend.title=element_text(size=7))
  #theme(legend.key.size = unit(0.1, "cm"))
  #  theme(plot.title = element_text(size=14),axis.text.y=element_blank(),axis.title.x=element_text(size = 14),axis.title.y=element_text(size = 14))

h5.repara<-ggplot(mu.var.hisse, aes(x=clone,y=value,group=Rates,colour=Rates,shape=Rates)) +
    geom_line(size=1) +
    geom_point(size=2)+
    ggtitle("Marginal variance- mu")+
  xlab("number of clones")+
  ylab("Marginal variance")+
   scale_colour_manual(values=cbbPalette[17:20])+
  theme_pubclean()+
  theme(legend.text=element_text(size=8),
        legend.title=element_text(size=8))

# Marginal variances and eigenvalues
figureTogether2<-ggarrange(nrow = 3,ncol = 2, h3.turn,h3.repara,h4.turn, h4.repara, h5.turn,h5.repara,labels = c("A","D","B","E","C","F"))

ggsave(filename="FigureS3_high.png", plot=figureTogether, device="png",dpi=500)
ggsave(filename="FigureS4_high.png", plot=figureTogether2, device="png",dpi=500)


```

